In [4]:
# ! pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [27]:

sampl = np.round(np.random.uniform(1, 5, (2,2)), 2)
sampl

array([[2.19, 2.31],
       [4.88, 3.22]])

In [33]:
def create_random_matrix(low, high, size, round_to):
    mat = np.round(np.random.uniform(low, high, size), round_to)
    return mat

def matrix_multiplication(mat1, mat2):
    return mat1.dot(mat2)

def start():
    turn = 0
    while True:
        if turn > 0:
            to_continue = input("Wanna continue (y or n):")
            if to_continue == "n":
                print("bye bye !")
                break
        turn += 1
        print("Start....\n")
        print("-----------\nMatrix :-")
        row_mat_1 = int(input("Matrix-1 Row count:"))
        col_mat_1 = int(input("Matrx-1 Column count:"))
    
        row_mat_2 = int(input("Matrix-2 Row count:"))
        col_mat_2 = int(input("Matrix-2 Column count:"))
    
        if col_mat_1 != row_mat_2:
            print("Rule Violated: Column count of matrix-1 should be equal to Row count of matrix-2 !!!")
            print("So again start...\n")
            continue
            
        print("Random numbers :-")
        low = float(input("Min random value:"))
        high = float(input("Max random value:"))
        round_to = int(input("Round for each random value:"))
    
        mat1 = create_random_matrix(low, high, (row_mat_1, col_mat_1), round_to)
        mat2 = create_random_matrix(low, high, (row_mat_2, col_mat_2), round_to)
        resultant_matrix = matrix_multiplication(mat1, mat2)
        print("\nMatrix-1 :-")
        print(mat1)
        print("\nMatrix-2 :-")
        print(mat2)
        print("\nResultant matrix :-")
        print(resultant_matrix)

    

In [34]:
start()

Start....

-----------
Matrix :-


Matrix-1 Row count: 2
Matrx-1 Column count: 3
Matrix-2 Row count: 3
Matrix-2 Column count: 10


Random numbers :-


Min random value: 1
Max random value: 100
Round for each random value: 9



Matrix-1 :-
[[43.9144164  73.32144841 91.4402432 ]
 [45.58720385 67.36100934 94.86426809]]

Matrix-2 :-
[[43.17600482 41.92498902 62.89982131 33.38083637 54.64227333 52.42023654
  91.93329418 38.87183035 46.07135789  5.27970448]
 [60.88818471 31.32372469 83.27103848 93.52482699 52.23622874 70.32783692
  24.0789607  66.49502956 58.11272519 29.99780683]
 [12.62191583  1.9507674  49.9916318  44.32218929 17.41495126 98.98152376
  13.94791309 22.0277832   9.8705655  63.00194589]]

Resultant matrix :-
[[ 7514.61000089  4316.19093413 13439.00906573 12376.1074928
   7822.04687289 16509.43756609  7078.10180116  8596.77147659
   7186.67288609  8192.2510409 ]
 [ 7267.13171913  4206.2988536  13219.06773852 12026.25778376
   7661.73015034 16516.85589485  7136.12348619  8340.87989268
   6951.16018     8238.00299558]]


Wanna continue (y or n): n


bye bye !
